export type JourneyMedia = {
  src: string;
  alt: string;
  label: string;
  caption: string;
  credit: string;
  license: string;
  sourceHref: string;
  objectPosition?: string;
};

function commonsSource(fileName: string) {
  return `https://commons.wikimedia.org/wiki/File:${encodeURIComponent(fileName).replace(/%2F/g, "/")}`;
}

const media = {
  shanghai: {
    src: "/journey-photos/shanghai.jpg",
    alt: "上海黄浦江沿岸实景",
    label: "城市实景 · 机场待确认",
    caption: "上海机场尚未确定，暂以城市实景表示返程终点。",
    credit: "Xiquinho Silva",
    license: "CC BY 2.0",
    sourceHref: commonsSource("Huangpu Park 20124-Shanghai (32208802494).jpg"),
  },
  kix: {
    src: "/journey-photos/kix.jpg",
    alt: "关西国际机场人工岛与航站楼实景",
    label: "目的地实景",
    caption: "关西国际机场全景，落地与返程都从这里衔接大阪。",
    credit: "Ankou1192",
    license: "CC BY-SA 4.0",
    sourceHref: commonsSource("関西国際空港全体写真20220811.jpg"),
  },
  osakaNight: {
    src: "/journey-photos/osaka-dotonbori.jpg",
    alt: "大阪道顿堀夜景实拍",
    label: "大阪南区实景",
    caption: "道顿堀夜景；难波、心斋桥住宿尚未定店时用于表示住宿区域。",
    credit: "Martin Falbisoner",
    license: "CC BY-SA 4.0",
    sourceHref: commonsSource("Dotonbori, Osaka, at night, November 2016.jpg"),
  },
  hozenji: {
    src: "/journey-photos/hozenji.jpg",
    alt: "大阪法善寺横丁石板小巷实景",
    label: "目的地实景",
    caption: "法善寺横丁的石板小巷，适合抵达日晚间慢走。",
    credit: "Mr.ちゅらさん",
    license: "CC BY-SA 4.0",
    sourceHref: commonsSource("Hozenji Yokocho 2023-11.jpg"),
    objectPosition: "center 58%",
  },
  usj: {
    src: "/journey-photos/usj.jpg",
    alt: "日本环球影城园区入口实景",
    label: "目的地实景",
    caption: "日本环球影城园区入口；实际开放与入园安排以当天官方信息为准。",
    credit: "Takashi Hososhima",
    license: "CC0",
    sourceHref: commonsSource("UNIVERSAL STUDIOS JAPAN ENTRANCE.jpg"),
  },
  kuromon: {
    src: "/journey-photos/kuromon.jpg",
    alt: "大阪黑门市场商店街实景",
    label: "目的地实景",
    caption: "黑门市场商店街，作为 USJ 后轻松日的早午餐起点。",
    credit: "Eric Salard",
    license: "CC BY-SA 4.0",
    sourceHref: commonsSource("KUROMON MARKET OSAKA (54676620980).jpg"),
  },
  shitennoji: {
    src: "/journey-photos/shitennoji.jpg",
    alt: "大阪四天王寺与城市天际线实景",
    label: "目的地实景",
    caption: "四天王寺与大阪南区天际线。",
    credit: "名古屋太郎",
    license: "CC BY-SA 3.0",
    sourceHref: commonsSource("Shitennoji & Abeno Harukas.jpg"),
  },
  keitakuen: {
    src: "/journey-photos/keitakuen.jpg",
    alt: "大阪庆泽园池泉庭园实景",
    label: "目的地实景",
    caption: "天王寺公园内的庆泽园，安排为低强度庭园休息段。",
    credit: "Laitche",
    license: "CC BY-SA 3.0",
    sourceHref: commonsSource("A Japanese garden scene from a chickee in Keitaku-en.jpg"),
  },
  tsutenkaku: {
    src: "/journey-photos/tsutenkaku.jpg",
    alt: "大阪新世界通天阁实景",
    label: "目的地实景",
    caption: "新世界街区与通天阁；体力不足时只逛街景、不必登塔。",
    credit: "Sakai Yayoi",
    license: "CC0",
    sourceHref: commonsSource("New Tsutenkaku, Osaka.jpg"),
    objectPosition: "center 45%",
  },
  nipponbashi: {
    src: "/journey-photos/nipponbashi.jpg",
    alt: "大阪日本桥街区实景",
    label: "目的地实景",
    caption: "日本桥电电城所在街区，集中安排动漫、电器与模型店。",
    credit: "Oilstreet",
    license: "CC BY 2.5",
    sourceHref: commonsSource("Nipponbashi Osaka Japan01-r.jpg"),
  },
  kobeHerb: {
    src: "/journey-photos/kobe-herb.jpg",
    alt: "神户布引香草园实景",
    label: "目的地实景",
    caption: "布引香草园山景，是神户日从高处向海港推进的起点。",
    credit: "663highland",
    license: "CC BY 2.5",
    sourceHref: commonsSource("Kobe Nunobiki Herb Garden03n3200.jpg"),
    objectPosition: "center 38%",
  },
  kobeKitano: {
    src: "/journey-photos/kobe-kitano.jpg",
    alt: "神户北野异人馆街风见鸡馆实景",
    label: "目的地实景",
    caption: "北野异人馆街的风见鸡馆；神户牛餐厅未定时也用于表示附近用餐区域。",
    credit: "Manish Prabhune",
    license: "CC BY 4.0",
    sourceHref: commonsSource("Weathercock House Kobe Kitano Ijinkan 風見鶏の館（旧トーマス住宅）.jpg"),
  },
  kobeHarbor: {
    src: "/journey-photos/kobe-harbor.jpg",
    alt: "神户港塔与 Harborland 夜景实拍",
    label: "目的地实景",
    caption: "神户港与 Harborland 夜景，作为神户日的日落收尾。",
    credit: "そらみみ",
    license: "CC BY-SA 4.0",
    sourceHref: commonsSource("Kobe Port Tower and Harborland at night 20190202-2.jpg"),
  },
  kyotoStation: {
    src: "/journey-photos/kyoto-station.jpg",
    alt: "京都站站房实景",
    label: "住宿区域实景 · 非酒店照片",
    caption: "京都住宿暂定京都站附近；酒店确定前用站区实景占位。",
    credit: "EXECUTOR",
    license: "CC0",
    sourceHref: commonsSource("Kyōto Station.jpg"),
  },
  arashiyama: {
    src: "/journey-photos/arashiyama.jpg",
    alt: "京都岚山竹林小径实景",
    label: "目的地实景",
    caption: "岚山竹林小径；行程只短停拍照，把更多时间留给庭园与河岸。",
    credit: "Mitchwandrew",
    license: "CC BY 4.0",
    sourceHref: commonsSource("Arashiyama Bamboo Grove.jpg"),
    objectPosition: "center 58%",
  },
  tenryuji: {
    src: "/journey-photos/tenryuji.jpg",
    alt: "京都天龙寺曹源池庭园实景",
    label: "目的地实景",
    caption: "天龙寺曹源池庭园，是岚山当天的主要游览体验。",
    credit: "SElefant",
    license: "CC BY-SA 3.0",
    sourceHref: commonsSource("Tenryu-Ji Garden.jpg"),
  },
  togetsukyo: {
    src: "/journey-photos/togetsukyo.jpg",
    alt: "京都岚山渡月桥与桂川实景",
    label: "目的地实景",
    caption: "渡月桥与桂川河岸，以看山景和休息结束岚山段。",
    credit: "Basile Morin",
    license: "CC BY-SA 4.0",
    sourceHref: commonsSource("Togetsu-kyō bridge at golden hour, Kyoto, Japan.jpg"),
  },
  philosopher: {
    src: "/journey-photos/philosopher.jpg",
    alt: "京都哲学之道运河步道实景",
    label: "目的地实景",
    caption: "哲学之道运河步道，完整预留约 60–75 分钟。",
    credit: "Stephan Ridgway",
    license: "CC BY 2.0",
    sourceHref: commonsSource("Philosophers Walk, Kyoto (49073314072).jpg"),
    objectPosition: "center 60%",
  },
  nanzenji: {
    src: "/journey-photos/nanzenji.jpg",
    alt: "京都南禅寺水路阁实景",
    label: "目的地实景",
    caption: "南禅寺水路阁，从哲学之道向南自然衔接。",
    credit: "Jakub Hałun",
    license: "CC BY 4.0",
    sourceHref: commonsSource("Nanzenji aqueduct in Kyoto, 20240820 1157 5046.jpg"),
    objectPosition: "center 55%",
  },
  byodoin: {
    src: "/journey-photos/byodoin.jpg",
    alt: "京都宇治平等院凤凰堂实景",
    label: "目的地实景",
    caption: "平等院凤凰堂与阿字池；烟火日以庭园和博物馆为主。",
    credit: "GiveMeMollusks",
    license: "CC0",
    sourceHref: commonsSource("Byōdo-in Temple in Uji, Kyoto, Japan.jpg"),
  },
  ujiRiver: {
    src: "/journey-photos/uji-river.jpg",
    alt: "京都宇治川河岸实景",
    label: "目的地实景",
    caption: "宇治川河岸；茶歇后在这里放慢速度，再前往城阳会场。",
    credit: "Ctny",
    license: "CC BY-SA 4.0",
    sourceHref: commonsSource("View of Uji river.jpg"),
  },
  fireworks: {
    src: "/journey-photos/japan-fireworks.jpg",
    alt: "日本烟火大会氛围实拍",
    label: "烟火氛围参考 · 非城阳现场",
    caption: "真实日本烟火实拍，仅示意观赏氛围；不是本届城阳秋花火现场图。",
    credit: "DeltaWorks",
    license: "CC0",
    sourceHref: commonsSource("SplendidFireworks.jpg"),
  },
  kifune: {
    src: "/journey-photos/kifune.jpg",
    alt: "京都贵船神社灯笼参道实景",
    label: "目的地区域实景",
    caption: "贵船神社灯笼参道；本宫、奥宫与结社沿河连续参拜。",
    credit: "Chi King",
    license: "CC BY 2.0",
    sourceHref: commonsSource("貴船神社 Kibune Jinja (KYOTO-JAPAN) (4951368080).jpg"),
  },
  fushimi: {
    src: "/journey-photos/fushimi.jpg",
    alt: "京都伏见稻荷大社千本鸟居实景",
    label: "目的地实景",
    caption: "伏见稻荷大社千本鸟居；走到奥社奉拜所后折返，不登顶。",
    credit: "Balon Greyjoy",
    license: "CC0",
    sourceHref: commonsSource("20181110 Fushimi Inari Torii 4.jpg"),
  },
  todaiji: {
    src: "/journey-photos/todaiji.jpg",
    alt: "奈良东大寺大佛殿实景",
    label: "目的地区域实景",
    caption: "东大寺大佛殿；二月堂段暂共用东大寺区域实景。",
    credit: "Felix Filnkössl",
    license: "CC BY-SA 3.0",
    sourceHref: commonsSource("Todai-ji.jpg"),
  },
  kasuga: {
    src: "/journey-photos/kasuga.jpg",
    alt: "奈良春日大社石灯笼参道实景",
    label: "目的地区域实景",
    caption: "春日大社石灯笼参道；林间午餐点暂共用奈良公园东侧实景。",
    credit: "Ray in Manila",
    license: "CC BY 2.0",
    sourceHref: commonsSource("Kasuga Taisha, Nara.jpg"),
  },
} satisfies Record<string, JourneyMedia>;

function contextual(base: JourneyMedia, overrides: Partial<JourneyMedia>): JourneyMedia {
  return { ...base, ...overrides };
}

export const journeyMediaByPointId: Record<string, JourneyMedia> = {
  "shanghai-flight-placeholder": media.shanghai,
  kix: media.kix,
  "osaka-stay": contextual(media.osakaNight, {
    label: "住宿区域实景 · 非酒店照片",
    caption: "大阪住宿暂定难波／心斋桥；酒店确定前以相邻道顿堀夜景占位。",
  }),
  shinsaibashi: contextual(media.osakaNight, {
    label: "相邻街区实景",
    caption: "照片为相邻道顿堀夜景；心斋桥筋就在大阪南区同一晚间步行圈。",
  }),
  dotonbori: media.osakaNight,
  hozenji: media.hozenji,
  usj: media.usj,
  kuromon: media.kuromon,
  shitennoji: media.shitennoji,
  "tennoji-park": media.keitakuen,
  shinsekai: media.tsutenkaku,
  "den-den-town": media.nipponbashi,
  wanaka: contextual(media.osakaNight, {
    label: "餐厅候选 · 区域实景",
    caption: "餐厅尚未最终锁定；照片为难波晚间街区，不是门店照片。",
  }),
  nunobiki: media.kobeHerb,
  kitano: media.kobeKitano,
  mouriya: contextual(media.kobeKitano, {
    label: "餐厅候选 · 周边实景",
    caption: "Mouriya 尚待预订确认；照片为北野附近实景，不是餐厅门店照片。",
  }),
  meriken: media.kobeHarbor,
  harborland: media.kobeHarbor,
  "kyoto-stay": media.kyotoStation,
  "arashiyama-bamboo": media.arashiyama,
  tenryuji: media.tenryuji,
  togetsukyo: media.togetsukyo,
  maekawa: contextual(media.kyotoStation, {
    label: "餐厅候选 · 门店照待补",
    caption: "料理屋まえかわ尚待最终预订；暂显示京都住宿交通节点，不冒充门店实景。",
  }),
  philosopher: media.philosopher,
  nanzenji: media.nanzenji,
  byodoin: media.byodoin,
  "nakamura-uji": contextual(media.byodoin, {
    label: "餐厅候选 · 周边实景",
    caption: "中村藤吉平等院店在同一游览区；照片为平等院周边实景。",
  }),
  "uji-river": media.ujiRiver,
  joyo: media.fireworks,
  kifune: media.kifune,
  "kifune-okumiya": media.kifune,
  "kifune-yui": media.kifune,
  "fushimi-inari": media.fushimi,
  todaiji: media.todaiji,
  nigatsudo: media.todaiji,
  mizuya: contextual(media.kasuga, {
    label: "餐厅候选 · 周边实景",
    caption: "水谷茶屋位于奈良公园林间路线；照片为附近春日大社参道，不是门店照片。",
  }),
  kasuga: media.kasuga,
};

export function getJourneyMedia(pointId: string): JourneyMedia {
  return journeyMediaByPointId[pointId] ?? media.osakaNight;
}
