import type { JourneyConfig } from "@/app/guide-core/types";

export const kansaiJourney: JourneyConfig = {
  presentation: {
    eyebrow: "PLAY THE JOURNEY",
    titleLines: ["让整段旅程，", "沿着时间自己走起来。"],
    description: "点击播放后，地图会按真实日期逐段推进。每一步都说明几点从哪里出发、乘什么交通、几点到达，以及到达后停留多久；酒店与尚未锁定的餐厅暂用区域占位点。",
    phaseUnit: "个阶段",
    phaseSuffix: "可按天播放",
    map: {
      center: [34.83, 135.57],
      zoom: 8,
      ariaLabel: "渐进式旅行过程地图",
      note: "路线为动画示意，实际步行与换乘请使用下方 Google Maps 导航",
    },
    labels: {
      allDaysCode: "ALL",
      allDays: "九日全程",
      daySelectorAriaLabel: "选择要播放的日期",
      progress: "全程进度",
      stepSelectorAriaLabel: "选择动画阶段",
      day: "DAY",
      step: "STEP",
      departure: "从哪里 / 何时出发",
      arrival: "预计几点到",
      stay: "到达后停留",
      route: "怎么走",
      navigation: "打开这一段 Google Maps 导航 ↗",
      controlsAriaLabel: "动画播放控制",
      previousAriaLabel: "上一步",
      nextAriaLabel: "下一步",
      play: "播放",
      pause: "暂停",
      replay: "重新播放",
      speedAriaLabel: "播放速度",
      nearbyStepsAriaLabel: "当前阶段前后步骤",
      unknownTime: "待定",
    },
  },
  supplementalPlaces: [
    {
      id: "shanghai-flight-placeholder",
      name: "上海出发机场 · 待确认",
      area: "kansai",
      category: "spot",
      position: [31.2304, 121.4737],
      dates: ["09.29", "10.07"],
      meta: "航班起降机场占位",
      googleQuery: "Shanghai",
    },
  ],
  beforeSteps: [
    {
      id: "09.29-shanghai-kix",
      date: "09.29",
      segment: "上海出发 · 航班占位",
      segmentNote: "当前只确认 9 月 29 日 14:00 抵达关西；上海具体机场与航班号以机票为准。",
      fromPlaceId: "shanghai-flight-placeholder",
      toPlaceId: "kix",
      mode: "国际航班",
      icon: "✈",
      duration: "约 4 小时 · 具体航班待确认",
      departurePlan: "上海出发机场｜暂按 10:00 起飞",
      arrivalPlan: "关西国际机场｜14:00 落地",
      stayPlan: "入境、取行李约 80–100 分钟；15:20–15:40 前往南海站",
      route: "上海 → 大阪关西国际机场；机场与航班号暂用占位信息。",
      timingStatus: "部分核实",
    },
  ],
  afterSteps: [
    {
      id: "10.07-kix-shanghai",
      date: "10.07",
      segment: "返沪航班 · 到达时间待补",
      segmentNote: "返程固定为 10 月 7 日 12:00 从关西机场起飞；上海落地机场与时间以最终机票为准。",
      fromPlaceId: "kix",
      toPlaceId: "shanghai-flight-placeholder",
      mode: "国际航班",
      icon: "✈",
      duration: "以最终机票为准",
      departurePlan: "关西国际机场｜12:00 起飞",
      arrivalPlan: "上海｜到达机场与时间待确认",
      stayPlan: "落地后旅程结束",
      route: "大阪关西国际机场 → 上海；返沪到达信息暂用占位点。",
      timingStatus: "部分核实",
    },
  ],
  placeholderLabels: {
    byPlaceId: {
      "shanghai-flight-placeholder": "航班终点占位",
    },
    byCategory: {
      stay: "住宿区域占位",
      restaurant: "餐厅候选点",
    },
  },
  transitIcons: {
    步行: "→",
    铁路: "▤",
    "铁路＋巴士": "▣",
    "缆车＋步行": "↟",
  },
};
